#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: ${S_EUREKA_HOST}

zuul:
  routes:
    proxy-service:
      url: http://proxy-service:8080
    eureka:
      url: http://eureka-service:8080
    api-gateway:
      url: forward:/catalog-service/favorites/
    by-id:
      url: forward:/catalog-service/position/true/byId/
    rec:
      url: forward:/catalog-service/rec/true/byId/
    rec-1:
      url: forward:/catalog-service/rec1/true/byId/
    positions:
      url: forward:/catalog-service/position/true/trueSettings/
    ml-team-2-service:
      url: http://ml-team-2-service:80
    ml-description-based-recommendation-service:
      url: http://ml-description-based-recommendation-service:5000
    ml4-recommendation-service:
      url: http://segandrec-service:5000
    ml3-recommendation-service:
      url: http://ml3-recommendation-service:8000
    demo-service:
      url: http://demo-service:8080
    demo-catalog-service:
      url: http://demo-catalog-service:8080
    user-service:
      url: http://user-service:8080
    am-parser-service:
      url: http://am-parser-service:8080
    winelab-parser-service:
      url: http://winelab-parser-service:8080
    simple-parser-service:
      url: http://simple-parser-service:8080
    winestyle-parser-service:
      url: http://winestyle-parser-service:8080
    crossroad-parser-service:
      url: http://crossroad-parser-service:8080
    lenta-parser-service:
      url: http://lenta-parser-service:8080
    catalog-service:
      url: http://catalog-service:8080
    deployment-service:
      url: http://deployment-service:8080
    notification-service:
      url: http://notification-service:8080
server:
  port: 8080